### ISSUE TITLE
Improve read me

### ISSUE THREAD

**Issue by theStratus** [MortezaBashsiz/nipovpnbash#1]
Thanks for the repository. I suggest adding this description at the beginning of the readme.md

`
# What is this?
This is an easy installation script to help you config these VPN protocols on your VPS.

* shadowsocks+obfs
* v2ray+vmess
* v2ray+vmess+ws
* trojan

# Requirements 
1. an external VPS (outside Iran) 
2. an internal VPS (Inside Iran)
3. Debian 11 as the OS of both VMs

A video guide on the usage can be found in [Youtube](https://youtu.be/jO-1O1BJ6rE). 
`

**Comment by MortezaBashsiz** [comment]
Thanks
Done
