### ISSUE TITLE
نصب اینترنال

### ISSUE THREAD

**Issue by ramindoroozeh** [MortezaBashsiz/nipovpnbash#10]
سلام منظورت از اینترنال و اکسترنال چیه ؟

**Comment by MortezaBashsiz** [comment]
سلام
داخل ایران و خارج ایران
اگه ریدمی رو بخونی متوجه میشی

**Comment by ramindoroozeh** [comment]
به مورد دیگه ssh key روی هر دو سرور باشه منظورم اینه ایران روی خارج و بلعکس!؟

**Comment by MortezaBashsiz** [comment]
درود
شما از هرجا که اجرا میکنید اسکریپت رو باید کلید ssh درست کنید و اونو کپی کنید روی هردو سرور اینترنال و اکسترنال

**Comment by ramindoroozeh** [comment]
و همچنان ارور های عجیب و غربب نمیدونم کجای کارم اشتباهه

**Comment by ramindoroozeh** [comment]
E: Unable to locate package v2ray
bad port "root@22"

**Comment by MortezaBashsiz** [comment]
بله این مشکل از سمت کد بود
دیشب برطرف شد
یکبار مجدد پول کنید درست میشه

**Comment by ramindoroozeh** [comment]
درست شد ممنون فقط خیلی جذاب نیست

**Comment by ramindoroozeh** [comment]
مرتضی جان مممنون از این همه وقتی که میزارید
الان ارور
arvan.sh: line 27: jq: command not found
arvan.sh: line 27: jq: command not found 
داریم

**Comment by MortezaBashsiz** [comment]
درود 
این یعنی باید jq رو نصب کنید
مثلا روی دبیانی ها

apt install jq
کلا هرچیزی که مثل این باشه
salam: command not found
یعنی باید پکیج سلام رو نصب کنید

**Comment by ramindoroozeh** [comment]
مخلص بله این سوتی خودم بود حواسم نبود
و سرور عالی نصب و راه اندازی شد با پینگ تایم پایین ولی صفحه باز نمیشه به هیچ عنوان 
ایا باید پروکسی cdn فعال باشه؟

**Comment by MortezaBashsiz** [comment]
اگه با روش cdn نصب کردید بله باید فعال باشه توی آروان
اگه نه که نیازی نیست

**Comment by ramindoroozeh** [comment]
با روش cdn نصب کردم ولی وقتی میزارم رو gheychi اصلا پیج باز نمیکنه ادرس و میزارم رو اصلی باز میکنه

**Comment by MortezaBashsiz** [comment]
این دیگه هرچی هست سمت آروانه
شاید یکم طول بکشه
یبار دیگه اجرا کنید شاید درست بشه
