### ISSUE TITLE
error in tojan installation

### ISSUE THREAD

**Issue by kazem3d** [MortezaBashsiz/nipovpnbash#11]
during the installation of trojan this error is occurred
![Screenshot_2022-12-18_19-49-34](https://user-images.githubusercontent.com/46394776/208308795-93de0bb4-fe3b-4790-a1ba-4aee3bc2eb7d.png)

**Comment by MortezaBashsiz** [comment]
The issue is resolved
Thanks for your contribution

**Comment by kazem3d** [comment]
Thank you!

**Comment by kazem3d** [comment]
script run correctly
but at the end it gives me : server ip+port+password
how can i use that
there is no url like vmess?

**Comment by MortezaBashsiz** [comment]
You have to install Igniter - Trojan Android Client 
Do not forget to disable Verify Certificate

**Comment by kazem3d** [comment]
Ok, thanks.
