### ISSUE TITLE
ERR: Domain creation faild

### ISSUE THREAD

**Issue by 0xAsghar** [MortezaBashsiz/nipovpnbash#13]
After entering the domain I get the following error:

arvan.sh: line 27: jq: command not found
(23) Failed writing body
arvan.sh: line 27: jq: command not found
(23) Failed writing body
ERR: Domain creation faild

**OS: Ubuntu 20.04

**Comment by ParsaGachkar** [comment]
looks like there is a dependency issue try running `apt install jq` before running the script.

**Comment by 0xAsghar** [comment]
Exactly, thanks
