### ISSUE TITLE
ERROR: Domain creation failed

### ISSUE THREAD

**Issue by bahmanworld** [MortezaBashsiz/nipovpnbash#18]
It failed on domain step.

Error: `Domain creation failed.`
Domain: `*.ir`

I use it without any VPN but still face this error.

**Comment by MortezaBashsiz** [comment]
Could you try to add the domain manually and test it in arvan panel?

**Comment by bahmanworld** [comment]
Yes. 
I can add `ir` domains manually and they work fine on Arvan Panel.

My VPS:
Server: `Hetzner Cloud`
Country: `USA`
OS: `Ubuntu 22.04`

![Screenshot 2022-12-27 185928](https://user-images.githubusercontent.com/5371898/209687907-192e034b-4598-4ead-ba44-e5ad00d02108.png)
☝️ I also run script on Debian 11, same error.

**Comment by tavangar79** [comment]
i have this problem too
arvan.sh: line 27: jq: command not found
(23) Failed writing body
arvan.sh: line 27: jq: command not found
(23) Failed writing body
ERR: Domain creation faild

**Comment by itbity** [comment]
i have this problem
> Please enter your domain. For example it like (sudoer.info)
salamti.info
arvan.sh: line 27: jq: command not found
arvan.sh: line 27: jq: command not found
ERR: Domain creation faild

**Comment by bahmanworld** [comment]
( @tavangar79 | @certifiedtruecopy )
to fix `jq: command not found` error, use following command before using `bash nimovpn.sh`:

```
apt update -y && apt upgrade -y && apt install jq
```

**Comment by MortezaBashsiz** [comment]
OK
So let's t-shoot it
Please run the following command and return the output
This command will create a domain manually by curl command

`curl -s -XPOST -H "Authorization: Apikey APIKEY" -H "Content-Type: application/json" -d "{ \"domain\": \"DOMAINNAME\", \"domain_type\": \"full\", \"plan_level\": 1 }" https://napi.arvancloud.ir/cdn/4.0/domains/dns-service`

NOTE: APIKEY, DOMAINNAME needs to be replaces by your own data

**Comment by MortezaBashsiz** [comment]
Issue closed
Reopen it if your issue is not resolved
