### ISSUE TITLE
Setting up V2RAY using only an external VPS

### ISSUE THREAD

**Issue by mazdakdev** [MortezaBashsiz/nipovpnbash#2]
Since nowadays there isn't permanent nationalization in Iran's network,
it would be better to add an feature for using this script in only an external VPS.

Best Regards,

**Comment by MortezaBashsiz** [comment]
Hi
Sure
Will do

**Comment by MortezaBashsiz** [comment]
Done
You can check it now

**Comment by mazdakdev** [comment]
Thanks for your support
