### ISSUE TITLE
ERR: SSH connectivity

### ISSUE THREAD

**Issue by MasoudLabafi66** [MortezaBashsiz/nipovpnbash#20]
> #######################################
> Domain is active in Arvan Now goint to add records
> Enter your Server IP like IP.IP.IP.IP
IP.IP.IP.IP
> Record created by name gheychivpn.masoudcdn.ml
> SSH port for Arvan server NULL (default 22)

ERR: SSH connectivity is not OK with user root to IP.IP.IP.IP and port 22

what should be done to fix the error?

**Comment by alemsas** [comment]
I have the same error!
I do ssh to my server with root user on 22 port!
And I have gotten this error
ERR: SSH connectivity is not OK with user root to IP x.x.x.x and port 22.
also I have permit the ssh on firewall

**Comment by MortezaBashsiz** [comment]
This is not related to firewall
You Must be able to ssh without pass and with ssh-key
For more information see this video
https://youtu.be/ZB6MxNXqm2A
