### ISSUE TITLE
issue when install v2ray on external server

### ISSUE THREAD

**Issue by gholamrezaeipt** [MortezaBashsiz/nipovpnbash#22]
Reading package lists... Done
W: GPG error: https://apt.v2fly.org stable InRelease: The following signatures were invalid: EXPKEYSIG B24ECFE5FF75D381 V2Fly Developers <dev@v2fly.org>
W: The repository 'https://apt.v2fly.org stable InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by MortezaBashsiz** [comment]
This is because the repository is not authenticated (Don't know why)
Please try to search about how to authenticate a repository in Ubuntu

**Comment by mohaa7** [comment]
```
gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv B24ECFE5FF75D381
gpg --export --armor B24ECFE5FF75D381 | sudo apt-key add -
```

`apt-key list`
> /etc/apt/trusted.gpg
> pub   rsa4096 2020-06-02 [SC] [expired: 2023-01-01]
      E2E3 5E27 914F B007 C0D4  B6DD B117 BA3B E8B4 94A7
> uid           [ **expired**] V2Fly Developers <dev@v2fly.org>

As you see in the above output, the key has been expired!
