### ISSUE TITLE
Fail to detect internet connection: io: read/write on closed pipe

### ISSUE THREAD

**Issue by gholamrezaeipt** [MortezaBashsiz/nipovpnbash#23]
Hi
i used your script to run vpn
everything seems OK but i have a problem with gheychivpn.domain.x:443 when try to connect but i'm ok with vpn.domain.x:443

both cname and subdomain is set in arvan cloud and my external server is ok but with v2rayng client i get this error:
Fail to detect internet connection: io: read/write on closed pipe

**Comment by MortezaBashsiz** [comment]
It may be related to your cloud config
Please try it again no need to clear everything just run the script again 
Some times The CDN provider api does not work correctly
