### ISSUE TITLE
Nginx Issue on ```both``` method using v2ray+vmess+ws

### ISSUE THREAD

**Issue by nekooei** [MortezaBashsiz/nipovpnbash#24]
hi,
when I am trying to run nipovpn.sh with internal and external server using v2ray+vmess+ws, got the error below

![error](https://user-images.githubusercontent.com/12533428/210365430-a7caf30b-ffc7-404a-bc1b-9e1a2bde4a59.png)

**Comment by MortezaBashsiz** [comment]
Hi
What is you distrobution?

**Comment by nekooei** [comment]
Hi,
both servers are Ubuntu 20.04

**Comment by MortezaBashsiz** [comment]
Interesting
By some reason, it was not able to install the v2ray package
If it is OK for you, please use Debian 11

**Comment by nekooei** [comment]
thanks
