### ISSUE TITLE
Certbot failed to authenticate domain

### ISSUE THREAD

**Issue by mahmoodkohansal** [MortezaBashsiz/nipovpnbash#25]
There is some problem in creating letsencrypt with bellow 

> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Requesting a certificate for vpn.kazem.skin

> Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: vpn.kazem.skin
  Type:   connection
  Detail: 5.161.70.233: Fetching http://vpn.kazem.skin/.well-known/acme-challenge/yyz5CskiIwEt9CTPdMsqxzHQ8HbWoIVu2T4LgS_4vFs: Timeout during connect (likely firewall problem)

> Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.
> Job for nginx.service failed because the control process exited with error code.
> See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.

**Comment by MortezaBashsiz** [comment]
Hi
Make sure to execute this script on a clean and fresh server

**Comment by mahmoodkohansal** [comment]
Hi, Thanks.
I deleted the server and create another one and the service started.
There is a new problem, the v2ray service is up but it doesn't work. how can I find the access.log file or error.log file to debug it?

**Comment by MortezaBashsiz** [comment]
You can reach the v2ray log with `journalctl -xf -u v2ray.service`
And nginx logs are in `/var/log/nginx`
