### ISSUE TITLE
"ERR: Domain creation failed" 

### ISSUE THREAD

**Issue by rosasabeti** [MortezaBashsiz/nipovpnbash#27]
I tried using `bash nipovpn.sh` and it failed with the error: `ERR: Domain creation failed`

**Steps to reproduce:**

1. Created a domain on namecheap.
2. Created an ubuntu machine on digitalocean.
3. Generated an Api Key (User machine) in Arvancloud as explained in your [video](https://youtu.be/_OiNxRbjdpg?t=1168)
4. Ran the script from my Linux machine.
5. ApiKey authenticated successfully.
6. Domain creation failed.

**Note:** Arvan is generating the API key differently than you demonstrated in your video. I don't think that matters though as it's passing the authentication step successfully.

**ArvanCloud**
![1](https://user-images.githubusercontent.com/124227579/216227705-24acc5d2-d523-45d6-86a5-d39b5cdcd7a4.png)

**Namecheap**
![4](https://user-images.githubusercontent.com/124227579/216227743-eb8012f4-22e2-4313-946e-76604c938aa0.png)

**Script Result**
![3](https://user-images.githubusercontent.com/124227579/216227779-ea505b56-de2a-44fd-bb35-8110d3f6f89a.png)

**Comment by MortezaBashsiz** [comment]
Hi
It could be related to the user machine permissions
I think you should grant the permission somewhere in your Arvan panel to the created user machine

**Comment by Dicordfa** [comment]
> Hi It could be related to the user machine permissions I think you should grant the permission somewhere in your Arvan 
>panel to the created user machine

Hi Morteza,
No, please see the new Arvan Cloud api panel and test this script again ([see this](https://docs.arvancloud.ir/fa/developer-tools/api/api-key))
In the new panel, there is no place at all to increase access
Apparently, the script has a problem and does not work
Please debug and release an update if possible
Thanks

**Comment by MortezaBashsiz** [comment]
Hi
Yes I am aware of that and already tested it with the new machine user structure
Works fine Here I will put my configurations on Arvan

This is my machine user
![image](https://user-images.githubusercontent.com/19620677/216590967-a109ee6a-7491-4dfc-bd28-4edd01580e87.png)

This is my workspace polices
![image](https://user-images.githubusercontent.com/19620677/216591088-7a40d3e5-823a-42c2-81ab-8ed26b3f75ec.png)
![image](https://user-images.githubusercontent.com/19620677/216591170-c75ffb1a-2535-4012-8c99-6a5b45719fd5.png)

**Comment by Dicordfa** [comment]
> Hi Yes I am aware of that and already tested it with the new machine user structure Works fine Here I will put my configurations on Arvan
> 
> This is my machine user ![image](https://user-images.githubusercontent.com/19620677/216590967-a109ee6a-7491-4dfc-bd28-4edd01580e87.png)
> 
> This is my workspace polices ![image](https://user-images.githubusercontent.com/19620677/216591088-7a40d3e5-823a-

Access polices is not required when the owner has created an API machine user
The script does not log
Can't the log be saved somewhere so we can understand exactly where the error is?
I have exactly the same problem

**Comment by MortezaBashsiz** [comment]
This is not from this script side
You can replace your variables (apikey, domain) at the following curl command then check if your token has correct permission or not
```sh
curl -s -XPOST -H "Authorization: Apikey ad73d33f-token-7e83c9c44522" -H "Content-Type: application/json" -d '{ "domain": "sudoer.net", "domain_type": "full", "plan_level": 1 }' https://napi.arvancloud.ir/cdn/4.0/domains/dns-service
```
If you get `<title>Forbidden</title>` then your key is not working well and you should follow up with Arvan

**Comment by gitmoh2** [comment]
> > Hi Yes I am aware of that and already tested it with the new machine user structure Works fine Here I will put my configurations on Arvan
> > This is my machine user ![image](https://user-images.githubusercontent.com/19620677/216590967-a109ee6a-7491-4dfc-bd28-4edd01580e87.png)
> > This is my workspace polices ![image](https://user-images.githubusercontent.com/19620677/216591088-7a40d3e5-823a-
> 
> Access polices is not required when the owner has created an API machine user The script does not log Can't the log be saved somewhere so we can understand exactly where the error is? I have exactly the same problem

do you figure out how to fix this?
