### ISSUE TITLE
Cloudflare Script

### ISSUE THREAD

**Issue by mahmoodkohansal** [MortezaBashsiz/nipovpnbash#29]
Hi, I want to use the Arvan script with Cloudflare CDN. In fact, I want to set up v2ray+vmess+ws+nginx+tls configuration in Cloudflare. 
Is it possible to set up the Arvan script and just move a domain from Arvan to Cloudflare (change in domain registrar and create A record and CNAME record in Cloudflare like Arvan)? Actually, I tried it but it has TLS handshake problems.
How can I change Arvan's script to work in Cloudflare?

**Comment by MortezaBashsiz** [comment]
It is not so easy to change script to support for Cloudflare
But if you install with script and move your domain from Arvan to CF it should work
