### ISSUE TITLE
 SSH connectivity is not OK

### ISSUE THREAD

**Issue by mohamad-rad** [MortezaBashsiz/nipovpnbash#4]
Hi, when I try to use the script for creating a VPN connection, at the start internal server IP, I get an error : 
ERR: SSH connectivity is not OK with user root to IP 1.2.3.4 and port 22

but when I use instant from Terminal with this command "ssh root@1.2.3.4" without any problem connecting to the internal server

**Comment by ampirshah** [comment]
> Hi, when I try to use the script for creating a VPN connection, at the start internal server IP, I get an error : ERR: SSH connectivity is not OK with user root to IP 1.2.3.4 and port 22
> 
> but when I use instant from Terminal with this command "ssh root@1.2.3.4" without any problem connecting to the internal server

yes, i exactly have the same problem

**Comment by rahimi-ali** [comment]
Source of the issue:
```$(ssh -q -o BatchMode=yes  -o StrictHostKeyChecking=no "$ip" -p "$port" "$cmd")```

As you can see when running ssh commands on the remote server user not set so bash will try to use your username, for example if you are logged in with user ali on your local system, it will try to run ssh commands on the remote server using ali user which may not exist and more importantly even if it exists, lacks root privileges.

Simple solution if you want to get it working is to login to root on your local system: ```su root```

**Comment by mohamad-rad** [comment]
> Source of the issue: `$(ssh -q -o BatchMode=yes -o StrictHostKeyChecking=no "$ip" -p "$port" "$cmd")`
> 
> As you can see when running ssh commands on the remote server user not set so bash will try to use your username, for example if you are logged in with user ali on your local system, it will try to run ssh commands on the remote server using ali user which may not exist and more importantly even if it exists, lacks root privileges.
> 
> Simple solution if you want to get it working is to login to root on your local system: `su root`

Or use like this >> root@1.2.3.4 , it's work too :)

**Comment by MortezaBashsiz** [comment]
Thank you for your contribution
The issue has been fixed in latest commit
