### ISSUE TITLE
DNS leak

### ISSUE THREAD

**Issue by mmahdisz** [MortezaBashsiz/nipovpnbash#5]
Hi,
I have DNS Leak with the shadowsocks + obfs.
What we can do to fix it?

**Comment by MortezaBashsiz** [comment]
Hi
Thanks
Are you using ubuntu 20.04?

**Comment by mmahdisz** [comment]
Thank you
My internal servers are 20.04 and my external ones are 18.04

**Comment by MortezaBashsiz** [comment]
Yes this is Ubuntu issue
It happens from time to time but this is not for all of them
Make sure to have a proper DNS config in resolve.conf

**Comment by mmahdisz** [comment]
I will check resolve.conf out, but as you say, this is only for Ubuntu.
Then I should probably use some other IPs and servers on Debian! :)
Thanks.
