### ISSUE TITLE
bug and ssh access is taken

### ISSUE THREAD

**Issue by kazem3d** [MortezaBashsiz/nipovpnbash#9]
سلام
در حین اجرای کد پس از نصب دیپندنسی ها از من پسورد میخواست ، به صورت زیر:
`darvin@191.331.56.67's password: `
در صورتی که اصلا روی سرور  191.331.56.67 کاربری به اسم darvin ندارم و این کاربر متعلق به سیستم لوکال من هست
هر پسوردی زدم قبول نکر و نهایت با کنسل کردن اون تمامی دسترسی ssh من گرفته شد :(  احتمالا به علت تغییراتی که اسکریپت توی ip tables انجام داده

**Comment by MortezaBashsiz** [comment]
درود
شما کد رو از نو pull کنید
نمیدونم آخرین بار کی pull کردید
این مشکل برطرف شده
این ایشو رو میبندم اگه مشکل داشتید مجدد بازش کنید و پیام بزارید تا باهم برطرف کنیم

**Comment by kazem3d** [comment]
من کد رو سه روز پیش pull کرده بودم

**Comment by MortezaBashsiz** [comment]
الان همچنان مشکل دارید؟

**Comment by kazem3d** [comment]
فعلا دسترسی به سرور ندارم ، اگر دسترسی پیدا کردم مجدد تست می کنم
فقط گفتم در جریان باشد
ممنون از زحماتتون

**Comment by MortezaBashsiz** [comment]
اوکی
قربانت
ولی اگه مشکل داشتی این ایشو رو باز کن مجدد

**Comment by MortezaBashsiz** [comment]
دوست عزیز
من تازگی یه تغییری دادم و پول کردم
در جریان باش
مرسی

**Comment by kazem3d** [comment]
سپاس
